// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl6HKVqvxYVt0ZA-vTJGz-rn-ZqHcExpc',
    appId: '1:719576140435:web:90d941b11877aadd07db66',
    messagingSenderId: '719576140435',
    projectId: 'taskhub-d7f7e',
    authDomain: 'taskhub-d7f7e.firebaseapp.com',
    databaseURL: 'https://taskhub-d7f7e-default-rtdb.firebaseio.com',
    storageBucket: 'taskhub-d7f7e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDNU1FBh6QsnS1c5uIRZsJ6otflBzxWsE',
    appId: '1:719576140435:android:98f7b42b4f3ed00607db66',
    messagingSenderId: '719576140435',
    projectId: 'taskhub-d7f7e',
    databaseURL: 'https://taskhub-d7f7e-default-rtdb.firebaseio.com',
    storageBucket: 'taskhub-d7f7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCeDjVrMyiTZNAZqydpy1W1SWGo1Vp1rA',
    appId: '1:719576140435:ios:45a34dacd19abe2907db66',
    messagingSenderId: '719576140435',
    projectId: 'taskhub-d7f7e',
    databaseURL: 'https://taskhub-d7f7e-default-rtdb.firebaseio.com',
    storageBucket: 'taskhub-d7f7e.firebasestorage.app',
    iosBundleId: 'com.eyosiyas.taskHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCeDjVrMyiTZNAZqydpy1W1SWGo1Vp1rA',
    appId: '1:719576140435:ios:45a34dacd19abe2907db66',
    messagingSenderId: '719576140435',
    projectId: 'taskhub-d7f7e',
    databaseURL: 'https://taskhub-d7f7e-default-rtdb.firebaseio.com',
    storageBucket: 'taskhub-d7f7e.firebasestorage.app',
    iosBundleId: 'com.eyosiyas.taskHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl6HKVqvxYVt0ZA-vTJGz-rn-ZqHcExpc',
    appId: '1:719576140435:web:311bc2e1f5112e9a07db66',
    messagingSenderId: '719576140435',
    projectId: 'taskhub-d7f7e',
    authDomain: 'taskhub-d7f7e.firebaseapp.com',
    databaseURL: 'https://taskhub-d7f7e-default-rtdb.firebaseio.com',
    storageBucket: 'taskhub-d7f7e.firebasestorage.app',
  );
}
